echo "projet/"
echo "├── assembly"
echo "│   ├── Sample1"
echo "│   │   ├── assembly_graph.fastg"
echo "│   ├── Sample2"
echo "│   │   ├── ..."
echo "│   └── Sample3"
echo "│       ├── ..."
echo "├── quality_control"
echo "│   ├── fastp"
echo "│   │   ├── ..."
echo "│   ├── fastqc"
echo "│   │   ├── ..."
echo "│   └── multiqc"
echo "│       ├── after"
echo "│       │   ├── ..."
echo "│       │   └── multiqc_report.html"
echo "│       └── before"
echo "│           ├── ..."
echo "├── reads"
echo "│   ├── ..."
echo "├── scrip_fastp.sh"
echo "└── scrip_spades.sh"
